---

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint roles/server
  ansible-lint roles/server

platforms:
- name: server-server
  image: ${MOLECULE_DISTRO:-centos:7}
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  privileged: yes
  command: ${MOLECULE_COMMAND:-"/usr/sbin/init"}
  groups: ['ambari_server']
  network_mode: bridge
  networks:
  - name: molecule-server
    links:
    - server-mariadb:db

- name: server-mariadb
  image: mariadb:10.2
  env:
    MYSQL_ROOT_PASSWORD: molecule
    MYSQL_PASSWORD: molecule
    MYSQL_DATABASE: molecule
    MYSQL_USER: molecule
  command: mysqld
  groups: ['db']
  network_mode: bridge
  networks:
  - name: molecule-server

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

...
