---

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: Restart ambari-server
  service:
    name: ambari-server
    state: restarted
  notify: 'Wait Server'

- name: Wait Server
  wait_for:
    port: '{{ ambari_port }}'
    host: 0.0.0.0
    delay: 1

- name: Configure DB connection
  block:

  - name: Set the Ambari Server database setup options
    set_fact:
      ambari_database_options: "-j {{ java_path }} \
                                --database={{ database | regex_replace('mariadb', 'mysql') }} \
                                --databasehost={{ database_options.external_hostname|default(ansible_fqdn,true) }} \
                                --databaseport={{ lookup('vars', database | regex_replace('mariadb', 'mysql') + '_port') }} \
                                --databasename={{ database_options.ambari_db_name }} \
                                --databaseusername={{ database_options.ambari_db_username }} \
                                --databasepassword={{ database_options.ambari_db_password }}"

  - name: Configure the Ambari JDBC driver
    command:
      cmd: /usr/sbin/ambari-server setup --jdbc-db={{ database | regex_replace('mariadb', 'mysql') }} --jdbc-driver={{ lookup('vars', database + '_jdbc_location') }}

  - name: Configure Ambari DB connection
    command:
      cmd: /usr/sbin/ambari-server setup -s {{ ambari_java_options|default("") }} {{ ambari_database_options|default("") }}
    notify: Restart ambari-server

  when: import_results.changed | bool

...