---

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint roles/repo
  ansible-lint roles/repo

platforms:
- name: repo
  image: ${MOLECULE_DISTRO:-centos:7}

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
