---

name: "klusters.ambari.agent"

on:
  push:
    paths:
    - 'roles/agent/**'
    - 'molecule/agent/**'
    - '.github/workflows/agent.yml'
    - 'molecule/common/**'
    - '!**/*.md'

    tags-ignore:
    - '*.*'

jobs:
  molecule:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    env:
      PY_COLORS: 1
      MOLECULE_DISTRO: ${{ matrix.molecule_distro.distro }}
      MOLECULE_COMMAND: ${{ matrix.molecule_distro.command }}

      AMBARI_YUM_URL: ${{ secrets.AMBARI_YUM_URL }}
      AMBARI_YUM_USERNAME: ${{ secrets.AMBARI_YUM_USERNAME }}
      AMBARI_YUM_PASSWORD: ${{ secrets.AMBARI_YUM_PASSWORD }}

      matrix:
        molecule_distro:
        - { "distro":"centos:7", "command":"/usr/sbin/init" }
        collection_role:
        - agent

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        path: ansible_collections/klusters/ambari

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Cache python packages
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/python_requirements.txt') }}

    - name: Install python packages
      working-directory: ansible_collections/klusters/ambari
      run: |
        pip install --upgrade --upgrade-strategy eager -r molecule/${{ matrix.collection_role }}/python_requirements.txt

    - name: Run tests
      working-directory: ansible_collections/klusters/ambari
      run: |
        molecule test -s ${{ matrix.collection_role }}
